### ISSUE TITLE
Mobile menu is missing

### ISSUE THREAD

**Issue by fizerkhan** [wbkd/ghost-wbkd#13]
In mobile, menu is not shown. I would expect to have top header as menu. That will be nice.

**Comment by Dreyfuzz** [comment]
A simple fix is to comment out...

````
*@media (max-width: 480px) {
  #taglist {
    display: none;
  }
````

... at the bottom of webkid.css. That stops the menu from hiding.

**Comment by g-div** [comment]
I'm closing this issue because of f7fba6409c84c12d255107070e5ac7afbc8b8392.
Feel free to open a pull-request if you come up with a generic solution.
Thank you!
