### ISSUE TITLE
Fatal Errors uploading to ghost(pro)

### ISSUE THREAD

**Issue by camerongmay** [wbkd/ghost-wbkd#16]
following error messages on upload. 

`Replace the {{image}} helper with {{img_url feature_image}} or {{img_url profile_image}}
Replace the {{@blog.cover}} helper with {{@blog.cover_image}}
Replace the {{#if image}} helper with {{#if feature_image}}, or {{#if profile_image}}
Replace the {{#if @blog.cover}} helper with {{#if @blog.cover_image}}`

**Comment by moklick** [comment]
Maybe this error occurs because of a new ghost version. Did you try to rename the variables?

**Comment by camerongmay** [comment]
I did try, but without much luck.

**Comment by jalexspringer** [comment]
I renamed to variables and all is working just fine - submitted a PR [here](https://github.com/wbkd/ghost-wbkd/pull/17).

**Comment by g-div** [comment]
We are merging the PR submitted by @jalexspringer and closing this issue.
Feel free to re-open it if the changes don't solve your problem.
