### ISSUE TITLE
Question: Syntax Highlighting

### ISSUE THREAD

**Issue by ChetanBhasin** [wbkd/ghost-wbkd#4]
Syntax Highlighting, as I can see, is available in the demo. How can we use it in our own instllation?

**Comment by moklick** [comment]
Prism is included in the page layout as you can see here https://github.com/wbkd/ghost-wbkd/blob/master/page.hbs#L8 .. To use it you just need to write something like:

```javascript
var Hapi = require('hapi');
var server = new Hapi.Server();
```

or

```bash
npm install --save topojson
```
