### ISSUE TITLE
Sidebar Issue - no ajax request

### ISSUE THREAD

**Issue by dancpm** [wbkd/ghost-wbkd#6]
Why there is no ajax request to fetch rss sidebar last article? theme still original clone, there is no modification
![no-rss](https://cloud.githubusercontent.com/assets/11609111/10626688/cec50248-77db-11e5-8f30-6575b41abd46.png)

**Comment by moklick** [comment]
We will check that. Thanks.

**Comment by moklick** [comment]
should work now, since we added jquery
